"""Add complete field to Order model

Revision ID: c95fd9d1060d
Revises: 4e2f9bd5400f
Create Date: 2024-08-08 18:21:58.200914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95fd9d1060d'
down_revision = '4e2f9bd5400f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('complete')

    # ### end Alembic commands ###
